name: Run Make Pull Request Report
on: pull_request

jobs:
  first-job:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: log test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          fetch-depth: 0
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh

      - name: Authenticate with GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token


      - name: Authenticate with GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      
      - name: Get PR number
        id: get_pr_number
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Fetch PR commits
        run: |
          gh pr view ${{ env.PR_NUMBER }} --json commits > pr_commits.json

      - name: Fetch PR diff
        run: |
          gh pr diff ${{ env.PR_NUMBER }} > pr_diff.txt
        # PRの差分（diff）を `pr_diff.txt` に保存
        
      - name: Fetch file changes in PR
        run: |
          gh api repos/${{ github.repository }}/pulls/${{ env.PR_NUMBER }}/files > pr_files.json

      - name: Get branch name
        run: echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV

      - name: Run JavaScript to show branch name
        run: node ./actions_job/hello.js
        env:
          BRANCH_NAME: ${{ env.BRANCH_NAME }}

      - name: Run JavaScript to show branch name
        run: node ./actions_job/handle_commits.js