name: Run Make Pull Request Report
on: pull_request

permissions:
  pull-requests: write
  contents: read

jobs:
  first-job:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: log test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          fetch-depth: 0
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh

      - name: Authenticate with GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token


      - name: Authenticate with GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      
      - name: Get PR number
        id: get_pr_number
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Fetch PR commits
        run: |
          gh pr view ${{ env.PR_NUMBER }} --json commits > pr_commits.json

      - name: Fetch PR diff
        run: |
          gh pr diff ${{ env.PR_NUMBER }} > pr_diff.txt
        # PRの差分（diff）を `pr_diff.txt` に保存
        
      - name: Fetch file changes in PR
        run: |
          gh api repos/${{ github.repository }}/pulls/${{ env.PR_NUMBER }}/files > pr_files.json

      - name: Get branch name
        run: echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV

      - name: Run JavaScript to show branch name
        run: node ./actions_job/handle_commits.js

      - name: Run script to create video
        run: node ./actions_job/create_video.js

      - name: Upload video artifact
        uses: actions/upload-artifact@v3
        with:
          name: PRのレビューをゆっくり解説
          path: output.mp4

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const artifactName = 'PRのレビューをゆっくり解説';
            const artifactPath = 'output.mp4';
            const con = github.context;

            const artifactUrl = `https://github.com/${con.repo.owner}/${con.repo.repo}/actions/artifacts`;
            const commentBody = `動画ファイルがアップロードされました: [${artifactName}](${artifactUrl})`;

            await github.issues.createComment({
              ...context.repo,
              issue_number: con.issue.number,
              body: commentBody
            });

      