name: Run Make Pull Request Report
on: pull_request

jobs:
  first-job:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: log test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Get branch name
        run: echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV

      - name: Run JavaScript to show branch name
        run: node ./actions_job/hello.js
        env:
          BRANCH_NAME: ${{ env.BRANCH_NAME }}

      - name: Run JS script to log commit info
        run: node ./actions_job/CommitLog.js
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}